from gridplayer.player.mixins.commands import PlayerCommandsMixin
from gridplayer.player.mixins.drag_n_drop import PlayerDragNDropMixin
from gridplayer.player.mixins.grid import PlayerGridMixin
from gridplayer.player.mixins.menu import PlayerMenuMixin
from gridplayer.player.mixins.minor import PlayerMinorMixin
from gridplayer.player.mixins.playlist import PlayerPlaylistMixin
from gridplayer.player.mixins.settings import PlayerSettingsMixin
from gridplayer.player.mixins.single_mode import PlayerSingleModeMixin
from gridplayer.player.mixins.video_blocks import PlayerVideoBlocksMixin
