from __future__ import annotations

from typing import Protocol

from gridplayer.utils.drop_zone import DropZone


class Layout(Protocol):
    def displayed_size(self) -> tuple[int, int]: ...
    def id_at(self, row: int, col: int) -> str | None: ...
    def order(self) -> list[str]: ...
    def add(self, video_ids: list[str]) -> list[str]: ...
    def remove(self, video_id: str) -> None: ...
    def contains(self, video_id: str) -> bool: ...
    def shuffle(self) -> None: ...
    def replace_id(self, old_id: str, new_id: str) -> None: ...
    def free_capacity(self) -> int | None: ...
    def drop(
        self,
        video_ids: list[str],
        row: int | None,
        col: int | None,
        zone: DropZone | None,
        *,
        is_replace: bool = False,
        src_id: str | None = None,
        dst_id: str | None = None,
    ) -> list[str]: ...
