from types import MappingProxyType

from gridplayer.utils.qt import translate

SUBMENUS = MappingProxyType(
    {
        "Jump (to)": {"title": translate("Actions", "Jump (to)"), "icon": "jump-to"},
        "Loop": {"title": translate("Actions", "Loop"), "icon": "loop"},
        "When Finished": {
            "title": translate("Actions", "When Finished"),
            "icon": "playback-finish",
        },
        "Speed": {"title": translate("Actions", "Speed"), "icon": "speed"},
        "Zoom": {"title": translate("Actions", "Zoom"), "icon": "zoom"},
        "Aspect": {"title": translate("Actions", "Aspect"), "icon": "aspect"},
        "Crop": {"title": translate("Actions", "Crop"), "icon": "crop"},
        "Transform": {"title": translate("Actions", "Transform"), "icon": "rotate"},
        "Deinterlace": {
            "title": translate("Actions", "Deinterlace"),
            "icon": "deinterlace",
        },
        "[ALL]": {"title": translate("Actions", "[ALL]"), "icon": "all"},
        "Grid": {"title": translate("Actions", "Grid"), "icon": "grid"},
        "Seek Sync": {"title": translate("Actions", "Seek Sync"), "icon": "seek-sync"},
        "Seek Others": {
            "title": translate("Actions", "Sync Others"),
            "icon": "seek-sync",
        },
        "Percent": {
            "title": translate("Actions", "Percent"),
            "icon": "seek-sync-percent",
        },
        "Playlist Settings": {
            "title": translate("Actions", "Playlist Settings"),
            "icon": "playlist-settings",
        },
        "Snapshots": {"title": translate("Actions", "Snapshots"), "icon": "snapshots"},
        "Save Snapshot": {"title": translate("Actions", "Save Snapshot")},
        "Delete Snapshot": {"title": translate("Actions", "Delete Snapshot")},
        "Tracks": {"title": translate("Actions", "Tracks"), "icon": "track"},
        "Audio Mode": {
            "title": translate("Actions", "Audio Mode"),
            "icon": "stereo-mode",
        },
        "Audio Delay": {
            "title": translate("Actions", "Audio Delay"),
            "icon": "delay",
        },
        "Subtitles": {"title": translate("Actions", "Subtitles"), "icon": "subtitles"},
        "Subtitle Delay": {
            "title": translate("Actions", "Subtitle Delay"),
            "icon": "delay",
        },
        "Add": {"title": translate("Actions", "Add"), "icon": "add"},
        "On Network Error": {
            "title": translate("Actions", "On Network Error"),
            "icon": "network-error",
        },
        "Playback": {"title": translate("Actions", "Playback"), "icon": "playback"},
        "Audio": {"title": translate("Actions", "Audio"), "icon": "audio"},
        "Video": {"title": translate("Actions", "Video"), "icon": "video"},
    }
)

SECTIONS = MappingProxyType(
    {
        "video_active": [
            "Play / Pause",
            "Stop",
            "---",
            "Single Mode ON / OFF",
            "Previous Video",
            "Next Video",
            "---",
            (
                "Audio",
                "Audio Track",
                (
                    "Audio Delay",
                    "Audio Delay: %v",
                    "---",
                    "Audio Delay Later",
                    "Audio Delay Earlier",
                    "Audio Delay Reset",
                ),
                (
                    "Audio Mode",
                    "Audio Mode - Original",
                    "Audio Mode - Stereo",
                    "Audio Mode - Reverse Stereo",
                    "Audio Mode - Left",
                    "Audio Mode - Right",
                    "Audio Mode - Dolby Surround",
                    "Audio Mode - Headphones",
                    "Audio Mode - Mono",
                ),
                "Audio Device",
                "---",
                "Audio Volume - Increase",
                "Audio Volume - Decrease",
                "Audio Volume - Mute / Unmute",
            ),
            (
                "Video",
                "Video Track",
                (
                    "Zoom",
                    "Zoom In",
                    "Zoom Out",
                    "Zoom Reset",
                ),
                (
                    "Aspect",
                    "Aspect Fit",
                    "Aspect Stretch",
                    "Aspect None",
                ),
                (
                    "Crop",
                    "Crop Left +",
                    "Crop Left -",
                    "Crop Top +",
                    "Crop Top -",
                    "Crop Right +",
                    "Crop Right -",
                    "Crop Bottom +",
                    "Crop Bottom -",
                    "---",
                    "Set Crop",
                    "Crop Reset",
                ),
                (
                    "Transform",
                    "Rotate 90",
                    "Rotate 180",
                    "Rotate 270",
                    "Flip Horizontally",
                    "Flip Vertically",
                    "Transpose",
                    "Anti-transpose",
                    "No Transform",
                ),
                (
                    "Deinterlace",
                    "Deinterlace Auto",
                    "Deinterlace On",
                    "Deinterlace Off",
                    "---",
                    "Deinterlace Mode - Auto",
                    "Deinterlace Mode - Discard",
                    "Deinterlace Mode - Blend",
                    "Deinterlace Mode - Mean",
                    "Deinterlace Mode - Bob",
                    "Deinterlace Mode - Linear",
                    "Deinterlace Mode - X",
                    "Deinterlace Mode - Yadif",
                    "Deinterlace Mode - Yadif (2x)",
                    "Deinterlace Mode - Phosphor",
                    "Deinterlace Mode - Film NTSC (IVTC)",
                ),
            ),
            (
                "Subtitles",
                "Subtitle Track",
                (
                    "Subtitle Delay",
                    "Subtitle Delay: %v",
                    "---",
                    "Subtitle Delay Later",
                    "Subtitle Delay Earlier",
                    "Subtitle Delay Reset",
                ),
            ),
            (
                "Playback",
                "Play Previous File",
                "Play Next File",
                "---",
                (
                    "Jump (to)",
                    (
                        "Percent",
                        "0%",
                        "10%",
                        "20%",
                        "30%",
                        "40%",
                        "50%",
                        "60%",
                        "70%",
                        "80%",
                        "90%",
                    ),
                    "Timecode",
                    "Random",
                    "---",
                    "Next frame",
                    "Previous frame",
                    "---",
                    "+1%",
                    "+5%",
                    "+10%",
                    "-1%",
                    "-5%",
                    "-10%",
                    "---",
                    "+5s",
                    "+15s",
                    "+30s",
                    "-5s",
                    "-15s",
                    "-30s",
                ),
                (
                    "Seek Others",
                    "Seek Others (Percent)",
                    "Seek Others (Timecode)",
                ),
                (
                    "Loop",
                    "Random Loop",
                    "---",
                    "Set Loop Start",
                    "Set Loop End",
                    "Loop Reset",
                ),
                (
                    "When Finished",
                    "When Finished Loop File",
                    "---",
                    "When Finished Next",
                    "When Finished Previous",
                    "When Finished Shuffle",
                    "---",
                    "When Finished Pause",
                    "When Finished Stop",
                    "When Finished Close",
                ),
                (
                    "Speed",
                    "Faster",
                    "Slower",
                    "Normal",
                ),
            ),
            "Stream Quality",
            "Rename",
            "Reload",
            "Auto Reload: %v",
            (
                "On Network Error",
                "On Network Error Show Error",
                "On Network Error Retry Times",
                "On Network Error Retry Forever",
                "---",
                "On Network Error Attempts: %v",
            ),
            "Close",
        ],
        "video_all": [
            (
                "[ALL]",
                "Play / Pause [ALL]",
                "Play [ALL]",
                "Pause [ALL]",
                "Stop [ALL]",
                "---",
                (
                    "Audio",
                    (
                        "Audio Mode",
                        "Audio Mode - Original [ALL]",
                        "Audio Mode - Stereo [ALL]",
                        "Audio Mode - Reverse Stereo [ALL]",
                        "Audio Mode - Left [ALL]",
                        "Audio Mode - Right [ALL]",
                        "Audio Mode - Dolby Surround [ALL]",
                        "Audio Mode - Headphones [ALL]",
                        "Audio Mode - Mono [ALL]",
                    ),
                    (
                        "Audio Delay",
                        "Audio Delay Set [ALL]",
                        "---",
                        "Audio Delay Later [ALL]",
                        "Audio Delay Earlier [ALL]",
                        "Audio Delay Reset [ALL]",
                    ),
                    "---",
                    "Audio Volume - Increase [ALL]",
                    "Audio Volume - Decrease [ALL]",
                    "Audio Volume - Mute [ALL]",
                    "Audio Volume - Unmute [ALL]",
                ),
                (
                    "Video",
                    (
                        "Zoom",
                        "Zoom In [ALL]",
                        "Zoom Out [ALL]",
                        "Zoom Reset [ALL]",
                    ),
                    (
                        "Aspect",
                        "Aspect Fit [ALL]",
                        "Aspect Stretch [ALL]",
                        "Aspect None [ALL]",
                    ),
                    (
                        "Crop",
                        "Crop Left + [ALL]",
                        "Crop Left - [ALL]",
                        "Crop Top + [ALL]",
                        "Crop Top - [ALL]",
                        "Crop Right + [ALL]",
                        "Crop Right - [ALL]",
                        "Crop Bottom + [ALL]",
                        "Crop Bottom - [ALL]",
                        "Crop Bottom - [ALL]",
                        "Crop Reset [ALL]",
                    ),
                    (
                        "Transform",
                        "Rotate 90 [ALL]",
                        "Rotate 180 [ALL]",
                        "Rotate 270 [ALL]",
                        "Flip Horizontally [ALL]",
                        "Flip Vertically [ALL]",
                        "Transpose [ALL]",
                        "Anti-transpose [ALL]",
                        "No Transform [ALL]",
                    ),
                ),
                (
                    "Subtitles",
                    (
                        "Subtitle Delay",
                        "Subtitle Delay Set [ALL]",
                        "---",
                        "Subtitle Delay Later [ALL]",
                        "Subtitle Delay Earlier [ALL]",
                        "Subtitle Delay Reset [ALL]",
                    ),
                ),
                (
                    "Playback",
                    "Play Previous File [ALL]",
                    "Play Next File [ALL]",
                    "---",
                    (
                        "Jump (to)",
                        (
                            "Percent",
                            "0% [ALL]",
                            "10% [ALL]",
                            "20% [ALL]",
                            "30% [ALL]",
                            "40% [ALL]",
                            "50% [ALL]",
                            "60% [ALL]",
                            "70% [ALL]",
                            "80% [ALL]",
                            "90% [ALL]",
                        ),
                        "Timecode [ALL]",
                        "Random [ALL]",
                        "---",
                        "Next frame [ALL]",
                        "Previous frame [ALL]",
                        "---",
                        "+1% [ALL]",
                        "+5% [ALL]",
                        "+10% [ALL]",
                        "-1% [ALL]",
                        "-5% [ALL]",
                        "-10% [ALL]",
                        "---",
                        "+5s [ALL]",
                        "+15s [ALL]",
                        "+30s [ALL]",
                        "-5s [ALL]",
                        "-15s [ALL]",
                        "-30s [ALL]",
                    ),
                    (
                        "Loop",
                        "Random Loop [ALL]",
                        "---",
                        "Set Loop Start [ALL]",
                        "Set Loop End [ALL]",
                        "Loop Reset [ALL]",
                    ),
                    (
                        "When Finished",
                        "When Finished Loop File [ALL]",
                        "---",
                        "When Finished Next [ALL]",
                        "When Finished Previous [ALL]",
                        "When Finished Shuffle [ALL]",
                        "---",
                        "When Finished Pause [ALL]",
                        "When Finished Stop [ALL]",
                        "When Finished Close [ALL]",
                    ),
                    (
                        "Speed",
                        "Faster [ALL]",
                        "Slower [ALL]",
                        "Normal [ALL]",
                    ),
                ),
                "---",
                "Reload [ALL]",
                "Auto Reload [ALL]",
            ),
            (
                "Snapshots",
                (
                    "Save Snapshot",
                    "Save Snapshot (1)",
                    "Save Snapshot (2)",
                    "Save Snapshot (3)",
                    "Save Snapshot (4)",
                    "Save Snapshot (5)",
                    "Save Snapshot (6)",
                    "Save Snapshot (7)",
                    "Save Snapshot (8)",
                    "Save Snapshot (9)",
                    "Save Snapshot (0)",
                ),
                (
                    "Delete Snapshot",
                    "Delete Snapshot (1)",
                    "Delete Snapshot (2)",
                    "Delete Snapshot (3)",
                    "Delete Snapshot (4)",
                    "Delete Snapshot (5)",
                    "Delete Snapshot (6)",
                    "Delete Snapshot (7)",
                    "Delete Snapshot (8)",
                    "Delete Snapshot (9)",
                    "Delete Snapshot (0)",
                ),
                "Load Snapshot (1)",
                "Load Snapshot (2)",
                "Load Snapshot (3)",
                "Load Snapshot (4)",
                "Load Snapshot (5)",
                "Load Snapshot (6)",
                "Load Snapshot (7)",
                "Load Snapshot (8)",
                "Load Snapshot (9)",
                "Load Snapshot (0)",
            ),
        ],
        "playlist": [
            (
                "Seek Sync",
                "Seek Sync (Disabled)",
                "Seek Sync (Percent)",
                "Seek Sync (Timecode)",
            ),
            (
                "Grid",
                "Shuffle Grid",
                "Shuffle Grid On Load",
                "---",
                "Rows First",
                "Columns First",
                "Fixed Grid",
                "---",
                "Size: %v",
                "Fit Cells",
                "Grid Size: %v",
                "Show All Cells",
            ),
            (
                "Playlist Settings",
                "Edit Playlist Settings",
                "---",
                "Pause Background Videos",
                "Pause When Minimized",
                "Disable Mouse Click Events",
                "Disable Mouse Wheel Events",
                "Disable Overlay",
                "Show Overlay Border",
                "Hide Overlay After Timeout",
            ),
        ],
        "program": [
            (
                "Add",
                "Add - Files",
                "Add - URL(s)",
                "Add - Clipboard",
                "Add - Recent Videos",
            ),
            "Open Playlist",
            "Open Playlist (Recent)",
            "Save Playlist",
            "Save Playlist As",
            "Close Playlist",
            "---",
            "Settings",
            "About",
            "---",
            "Fullscreen",
            "Minimize",
            "Quit",
        ],
    }
)
