#!/bin/bash

# If running from an extracted image, then export APPDIR
if [ -z "${APPIMAGE}" ]; then
    self="$(readlink -f -- $0)"
    here="${self%/*}"
    export APPDIR="${APPDIR:-${here}}"
fi

# Export SSL certificate
export SSL_CERT_FILE="${APPDIR}/opt/_internal/certs.pem"

export QT_PLUGIN_PATH="${APPDIR}/opt/python3.9/lib/python3.9/site-packages/PyQt5/Qt5/plugins/"
export QT_QPA_PLATFORM=xcb

export LD_LIBRARY_PATH="${APPDIR}/usr/lib:${APPDIR}/usr/lib/vlc:${LD_LIBRARY_PATH}"

"${APPDIR}/usr/bin/python3.9" "${APPDIR}/opt/python3.9/bin/gridplayer" "$@"
