name: release_flatpak

on:
  workflow_dispatch:
    inputs:
      custom_commit:
        description: 'Custom commit (at gridplayer-flatpak) to release as'
        required: false
        type: string
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

env:
  BUILD_PYTHON_VERSION: "3.10"

jobs:
  build_flatpak:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: extractions/setup-just@v4

      - name: Set up Python ${{ env.BUILD_PYTHON_VERSION }}
        uses: actions/setup-python@v7
        with:
          python-version: ${{ env.BUILD_PYTHON_VERSION }}

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0

      - name: Install requirements
        run: |
          sudo apt-get install -y desktop-file-utils appstream-util flatpak
          flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          flatpak install --user -y flathub org.kde.Sdk//5.15-25.08

      - name: Release
        env:
          GIT_USER: vzhd1701
          GIT_EMAIL: vzhd1701@gmail.com
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
          RELEASE_FOR_COMMIT: ${{ github.event.inputs.custom_commit }}
          FLATPAK_GIT_REPO: vzhd1701/gridplayer-flatpak
          FLATHUB_GIT_REPO: flathub/com.vzhd1701.gridplayer
        run: |
          just build-linux-flatpak-git
